import {
  mdiAccountGroupOutline,
  mdiAccountOutline,
  mdiAlert,
  mdiCalendar,
  mdiCalendarMonthOutline,
  mdiCalendarOutline,
  mdiCameraOutline,
  mdiChevronRight,
  mdiFileDocumentOutline,
  mdiPhone,
  mdiSend,
  //mdiHandset,
  mdiHandshakeOutline,
  mdiMagnify,
  mdiMinusCircle,
  mdiPlus,
  mdiPlusCircle,
  mdiRefresh,
  mdiTrayArrowUp,
} from '@mdi/js';

/** SVG-пути для Vuetify mdi-svg (строки mdi-* без шрифта не рисуются). */
export const appIcons = {
  accountGroupOutline: mdiAccountGroupOutline,
  accountOutline: mdiAccountOutline,
  alert: mdiAlert,
  calendarMonthOutline: mdiCalendarMonthOutline,
  calendarOutline: mdiCalendarOutline,
  calendar: mdiCalendar,
  cameraOutline: mdiCameraOutline,
  chevronRight: mdiChevronRight,
  fileDocumentOutline: mdiFileDocumentOutline,
  phone: mdiPhone,
  send: mdiSend,
  //handset: mdiHandset,
  handshakeOutline: mdiHandshakeOutline,
  magnify: mdiMagnify,
  minusCircle: mdiMinusCircle,
  plus: mdiPlus,
  plusCircle: mdiPlusCircle,
  refresh: mdiRefresh,
  trayArrowUp: mdiTrayArrowUp,
} as const;
